---
- name: Add KVM Repository
  template:
    src: kvm-common.repo.j2
    dest: /etc/yum.repos.d/kvm-common.repo
    owner: root
    group: root
    mode: '0644'

- name: Install Tools and KVM Software
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - wget
    - git
    - net-tools
    - bind-utils
    - bash-completion
    - nfs-utils
    - rsync
    - libvirt-python
    - libguestfs-tools
    - libvirt
    - qemu-kvm
    - virt-manager
    - virt-install
    - xorg-x11-apps
    - xauth
    - virt-viewer
    - libguestfs-xfs
    - iscsi-initiator-utils
  notify: enable_service

- name: Enable Nested Virtualisation
  template:
    src: kvm.conf.j2
    dest: /etc/modprobe.d/kvm.comnf
    owner: root
    group: root
    mode: '0644'

- name: Restart Libvirtd Service
  service:
    name: libvirtd
    state: restarted

