---
- name: Create .ssh folder
  file:
    path: /home/lab/.ssh
    state: directory
    owner: lab 
    group: lab
    mode: '0700'

- name: Create SSH key
  user:
    name: lab
    generate_ssh_key: yes
    ssh_key_comment: 'lab@services.home.swinney.io'
    ssh_key_bits: 2048
    ssh_key_file: "/home/lab/okd-lab/.ssh/id_rsa"
  become_user: lab

- name: Set authorized key
  authorized_key:
    user: lab
    state: present
    path: ~/okd-lab/.ssh/authorized_keys
    key: "{{ lookup('file', '/home/lab/okd-lab/.ssh/id_rsa.pub') }}"
  become_user: lab

- name: Set config
  template:
    src: config.j2
    dest: /home/lab/.ssh/config
    owner: lab
    group: lab
    mode: '0600'
  become_user: lab
    